version: "3.8"

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - /home/dima/certificates:/etc/ssl/certs
      - /home/dima/certificates:/usr/lib/ssl/certs:ro
    environment:
      - NGINX_SSL_CERT=/etc/ssl/certs/fullchain.pem
      - NGINX_SSL_KEY=/etc/ssl/certs/privkey.pem
    restart: always
    depends_on:
      - weave-server
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQLCLIENT_VERSION: 8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-prootpassword",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  weave-server:
    # comment it out for local development
    # image: dimdos95/prism-accounts:latest
    build: ./server
    working_dir: /usr/src/myapp
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env.prod
    restart: unless-stopped
    command: >
      sh -c "diesel migration run && /usr/local/bin/weave-server serve"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - /home/dima/certificates:/usr/lib/ssl/certs:ro

volumes:
  mysql_data:
networks:
  mynetwork:
    driver: bridge
