export const PROVIDERS = [
  {
    id: 'twitter',
    name: 'X',
    domain: 'x.com',
    link: 'https://x.com',
    providerId: 'e6fe962d-8b4e-4ce5-abcc-3d21c88bd64a',
    userCount: 25,
    description: 'Verifies twitter profile of user',
  },
  {
    id: 'google',
    name: 'Google',
    domain: 'gmail.com',
    link: 'https://gmail.com',
    providerId: 'f9f383fd-32d9-4c54-942f-5e9fda349762',
    userCount: 0,
    description: 'Verifies Google account ownership',
  },
  {
    id: 'linkedin',
    name: 'Linkedin',
    domain: 'linkedin.com',
    link: 'https://linkedin.com',
    providerId: 'a9f1063c-06b7-476a-8410-9ff6e427e637',
    userCount: 0,
    description: 'Verifies LinkedIn profile authenticity',
  },
  {
    id: 'github',
    name: 'Github',
    domain: 'github.com',
    link: 'https://github.com',
    providerId: '6d3f6753-7ee6-49ee-a545-62f1b1822ae5',
    userCount: 0,
    description: 'Verifies GitHub account ownership',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    domain: 'facebook.com',
    link: 'https://facebook.com',
    providerId: '823aa38f-7a42-4dd9-854e-7cf574100cc8',
    userCount: 0,
    description: 'Verifies Facebook account ownership',
  },
  {
    id: 'binance',
    name: 'Binance',
    domain: 'binance.com',
    link: 'https://binance.com',
    providerId: '2b22db5c-78d9-4d82-84f0-a9e0a4ed0470',
    userCount: 0,
    description: 'Verifies Binance KYC Level',
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    domain: 'coinbase.com',
    link: 'https://coinbase.com',
    providerId: '285a345c-c6a6-4b9f-9e1e-23432082c0a8',
    userCount: 0,
    description: 'Verifies Coinbase Completed KYC',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    domain: 'instagram.com',
    link: 'https://instagram.com',
    providerId: '3ad6946f-88f4-4958-9a8e-5271a831b5b8',
    userCount: 0,
    description: 'Verifies Instagram account ownership',
  },
] as const;
